#!/bin/sh
set -e 

. "$(dirname "$0")/_/husky.sh"
. .env

${ENABLE_HELM_DOCS:-true} && docker run --rm --volume "$PWD/chart/otomi:/helm-docs" -u $(id -u) jnorwood/helm-docs:latest 2&>/dev/null

${ENABLE_NPM_LINT:-true} && npm run lint-staged && npm run lint
