#!/bin/sh
set -e 

. "$(dirname "$0")/_/husky.sh"

. .env
docker run --rm --volume "$(pwd)/otomi/chart:/helm-docs" -u $(id -u) jnorwood/helm-docs:latest
${ENABLE_NPM_LINT:-true} && npm run lint-staged && npm run lint
